title: FaultX Support
description: FaultX Documentation
remote_theme: just-the-docs/just-the-docs # AKTIFKAN JIKA MAU LANGSUNG KE GIT ACTION
# theme: just-the-docs # AKTIFKAN JIKA TEST SERVER LOKAL

# Theme configuration
# Available color schemes: light and dark
color_scheme: light

# logo: "/assets/images/fx-support.svg"
favicon_ico: "/assets/images/favicon.ico"

nav_enabled: true

url: https://just-the-docs.github.io

aux_links:
  FaultX.Repair: https://faultxcloud.github.io/faultx.link/

# Callout styles configuration
callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red
  important:
    title: Important
    color: purple
  new:
    title: New
    color: green
  caution:
    title: Caution
    color: yellow

back_to_top: true
back_to_top_text: "Back to top â¬†"


footer_content: "Copyright &copy; 2025 <a href='https://faultxcloud.github.io/faultx.link/' target='_blank'>FaultX.Repair</a>"